name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-and-run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build app with Maven
        run: mvn clean package

      - name: Run tests
        run: mvn test

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-and-run-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar

      - name: Copy JAR to target directory
        run: mv app-jar/* target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            kacpi52/task2_spring:${{ env.SHORT_SHA }}